# ruff: noqa: E501
# This code is automatically generated by actions.yml and make generate-inputs
###START_INPUT_AUTOMATION###
INPUTS = {
    "action": {
        "description": "What action to take with this action. One of validate, check, or apply.\nValidate will validate your settings file, but not touch your repo.\nCheck will check your repo with your settings file and output a report of any drift.\nApply will apply the settings in your settings file to your repo\n",
        "default": "check",
    },
    "settings_file": {
        "description": "What yaml file to use as your settings. This is local to runner running this action.",
        "default": ".github/settings.yml",
    },
    "repo": {
        "description": "What repo to perform this action on. Default is self, as in the repo this action is running in",
        "default": "self",
    },
    "token": {"description": "What github token to use with this action.", "required": True},
}
###END_INPUT_AUTOMATION###
