name: "Yaml Repo Manager"
description: "Manage your Github repo(s) settings and secrets using Github Actions and a yaml file"
author: "Andrew Herrington"
inputs:
  action:
    description: What action to take with this action. One of validate, check, or apply. Validate will validate your settings file, but not touch your repo. Check will check your repo with your settings file and output a report of any drift. Apply will apply the settings in your settings file to your repo
    default: "check"
  settings_file:
    description: What yaml file to use as your settings. This is local to runner running this action.
    default: ".github/settings.yml"
  repo:
    description: What repo to perform this action on. Default is self, as in the repo this action is running in
    default: "self"
  github_server_url:
    description: Set a custom github server url for github api operations. Useful if you're running on GHE. Will try to autodiscover from env.GITHUB_SERVER_URL if left at default
    default: "none"
  token:
    description: What github token to use with this action.
    required: true
outputs:
  result:
    description: "Result of the action"
  diff:
    description: "Diff of this action, dumped to a json string"
runs:
  using: "docker"
  image: "docker://ghcr.io/andrewthetechie/gha-repo-manager:v1.8.0" # x-release-please-version
branding:
  icon: "settings"
  color: "blue"
