# Updates major version tag for GHA ease of use
name: Update Major Version Tag

on:
  push:
    tags:
      - "v*"

jobs:
  update-majorver:
    name: Update Major Version Tag
    if: github.repository_owner == 'andrewthetechie'
    runs-on: ubuntu-latest
    steps:
      - uses: nowactions/update-majorver@v1
