# This is a basic workflow to help you get started with Actions

name: Run Repo Manager

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "repo-manager"
  repo-manager:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run RepoManager
        #uses: andrewthetechie/gha-repo-manager@main
        uses: actuarysailor/gha-repo-manager@main
        with:
          # Apply your settings to the repo, can also be check to just check repo settings vs your file or validate, to validate your
          # file is valid
          action: apply
          settings_file: examples/settings.yml
          github_url: "https://github.com/api/v3"
          # need a PAT that can edit repo settings
          token: ${{ secrets.GITHUB_TOKEN }}
