name: Unit Test
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.11"
      - run: pip install -r Docker/builder/rootfs/requirements.txt
      - run: pip install -r requirements-dev.txt
      - name: Run pytest
        run: pytest
  test-docker-build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Docker/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
